import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/notofication">Notofication</Link>
        </li>
        <li>
          <Link to="/yourstats">Yourstats</Link>
        </li>
        <li>
          <Link to="/yourlists">Yourlists</Link>
        </li>
        <li>
          <Link to="/yourstories">YourStories</Link>
        </li>
        <li>
          <Link to="/yourstories1">YourStories1</Link>
        </li>
        <li>
          <Link to="/">Login</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/signupa">Signupa</Link>
        </li>
        <li>
          <Link to="/signup1">Signup1</Link>
        </li>
        <li>
          <Link to="/createstory">Createstory</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
